# docker-compose.yml
version: '3.8'
services:

  postgres:
    image: postgres:alpine3.17
    container_name: autotaskmanager
    restart: always
    environment:
      - POSTGRES_USER=keylogger
      - POSTGRES_PASSWORD=GHBDTN!@
      - POSTGRES_DB=commondb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
