# docker-compose.yml
version: '3.8'
services:

  postgres:
    container_name: postgres_todo
    image: auto_task_manager
    restart: always
    environment:
      - POSTGRES_USER=pokeradmin
      - POSTGRES_PASSWORD=GHBDTN!@
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
